DROP DATABASE IF EXISTS `login`;
CREATE DATABASE IF NOT EXISTS `login` DEFAULT CHARACTER SET 'UTF8';
USE `login`;
CREATE TABLE IF NOT EXISTS `user`(
`id` INT UNSIGNED AUTO_INCREMENT KEY,
`username` VARCHAR(20) NOT NULL UNIQUE,
`password` CHAR(32) NOT NULL,
`email` VARCHAR(50) NOT NULL,
`token` CHAR(32) NOT NULL COMMENT '激活token',
`token_exptime` INT UNSIGNED NOT NULL COMMENT 'token的过期时间',
`regTime` INT UNSIGNED NOT NULL,
`status` TINYINT UNSIGNED DEFAULT 0 COMMENT '0代表未激活，1代表激活'
);


